<?php
namespace App\Services;
use App\Models\Sales\Sale;use App\Models\Sales\Shipment;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Auth;use Illuminate\Validation\ValidationException;
class ShipmentService{
 public function generateNumber(): string{return DB::transaction(function(){ $p='SHP-'.now()->format('Ym').'-';$l=Shipment::withTrashed()->where('number','like',$p.'%')->lockForUpdate()->orderByDesc('id')->value('number');$s=$l?((int)substr($l,-5))+1:1;return $p.str_pad((string)$s,5,'0',STR_PAD_LEFT);});}
 public function createFromSale(Sale $sale,array $data): Shipment{if(!in_array($sale->status,['approved','partially_shipped'],true)) throw ValidationException::withMessages(['sale'=>'Sale must be approved/partially_shipped']);
 return DB::transaction(function() use($sale,$data){$shipment=Shipment::create(['number'=>$this->generateNumber(),'sale_id'=>$sale->id,'customer_id'=>$sale->customer_id,'warehouse_id'=>$data['warehouse_id']??$sale->warehouse_id,'shipment_date'=>$data['shipment_date'],'status'=>'draft','driver_name'=>$data['driver_name']??null,'vehicle_no'=>$data['vehicle_no']??null,'courier_name'=>$data['courier_name']??null,'tracking_number'=>$data['tracking_number']??null,'notes'=>$data['notes']??null]);
 $map=$sale->lines()->get()->keyBy('id'); foreach($data['lines'] as $l){$sl=$map[$l['sale_line_id']]??null; if(!$sl||$sl->sale_id!==$sale->id) throw ValidationException::withMessages(['lines'=>'Invalid sale line']); $rem=(float)$sl->qty_sold-(float)$sl->qty_shipped; if((float)$l['qty_shipped']>$rem+0.0000001) throw ValidationException::withMessages(['lines'=>'Qty shipped exceeds remaining']);
 $shipment->lines()->create(['sale_line_id'=>$sl->id,'item_id'=>$l['item_id'],'batch_id'=>$l['batch_id']??null,'facility_scheme_id'=>$l['facility_scheme_id']??null,'uom_id'=>$l['uom_id']??$sl->uom_id,'qty_ordered'=>$sl->qty_sold,'qty_already_shipped'=>$sl->qty_shipped,'qty_shipped'=>$l['qty_shipped'],'qty_base'=>$l['qty_base']??$sl->qty_base,'notes'=>$l['notes']??null]);}
 return $shipment->fresh('lines');});}
 public function postShipment(Shipment $shipment): Shipment{return DB::transaction(function() use($shipment){$shipment=$shipment->fresh(['sale.lines','lines']); if($shipment->status!=='draft') throw ValidationException::withMessages(['status'=>'Only draft can be posted']);
 $warehouseId=$shipment->warehouse_id?:$shipment->sale?->warehouse_id; if(!$warehouseId) throw ValidationException::withMessages(['warehouse_id'=>'Missing warehouse']);
 $usageId=DB::table('internal_usages')->insertGetId(['number'=>'DSP-'.$shipment->number,'warehouse_id'=>$warehouseId,'facility_scheme_id'=>null,'transaction_code'=>'SALES_SHIPMENT','outbound_number'=>$shipment->number,'sender_receiver_name'=>$shipment->customer?->customer_name,'department'=>'SALES','cost_center'=>'SALES','document_date'=>$shipment->shipment_date,'status'=>'DRAFT','notes'=>'Generated from Sales Shipment '.$shipment->number,'created_at'=>now(),'updated_at'=>now()]);
 foreach($shipment->lines as $line){$sl=$shipment->sale->lines->firstWhere('id',$line->sale_line_id);$rem=(float)$sl->qty_sold-(float)$sl->qty_shipped; if((float)$line->qty_shipped<=0|| (float)$line->qty_shipped>$rem+0.0000001) throw ValidationException::withMessages(['lines'=>'Invalid shipment qty']); DB::table('internal_usage_lines')->insert(['internal_usage_id'=>$usageId,'item_id'=>$line->item_id,'batch_id'=>$line->batch_id,'qty_used'=>$line->qty_shipped,'uom_id'=>$line->uom_id,'qty_base'=>$line->qty_base ?? $line->qty_shipped,'facility_scheme_id'=>$line->facility_scheme_id,'notes'=>$line->notes,'created_at'=>now(),'updated_at'=>now()]);}
 app(\App\Http\Controllers\Apps\InventoryPostingController::class)->postInternalUsage(request(),$usageId);
 foreach($shipment->lines as $line){$sl=$shipment->sale->lines()->lockForUpdate()->find($line->sale_line_id);$sl->update(['qty_shipped'=>(float)$sl->qty_shipped+(float)$line->qty_shipped]);}
 $sale=$shipment->sale()->with('lines')->first();$remaining=$sale->lines->sum(fn($l)=>(float)$l->qty_sold-(float)$l->qty_shipped);$sale->update(['status'=>$remaining>0?'partially_shipped':'fully_shipped']);
 $shipment->update(['dispatch_id'=>$usageId,'status'=>'posted','posted_by'=>Auth::id(),'posted_at'=>now()]); return $shipment->fresh(['sale','lines']);});}
 public function cancelShipment(Shipment $shipment,string $reason): Shipment{if($shipment->status!=='draft') throw ValidationException::withMessages(['status'=>'Only draft']);$shipment->update(['status'=>'cancelled','cancelled_by'=>Auth::id(),'cancelled_at'=>now(),'cancel_reason'=>$reason]);return $shipment;}
}
