<?php
namespace App\Http\Controllers\Apps\HumanResource;
use App\Http\Controllers\Controller;use App\Models\{Department,Employee,Position,User,EmployeeLicense};use Illuminate\Http\Request;use Illuminate\Support\Facades\Hash;use Inertia\Inertia;
class EmployeeController extends Controller { /* trimmed for brevity */
 public function index(Request $r){$cid=(int)($r->user()->company_id??1);$q=Employee::with(['department','position','licenses'])->where('company_id',$cid); if($s=$r->get('search')){$q->where(fn($w)=>$w->where('full_name','like',"%$s%")->orWhere('nik','like',"%$s%")->orWhere('employee_code','like',"%$s%"));} if($r->filled('department_id'))$q->where('department_id',$r->department_id); if($r->filled('position_id'))$q->where('position_id',$r->position_id); if($r->filled('status'))$q->where('is_active',$r->status==='active'); return Inertia::render('HumanResource/Employees/Index',['employees'=>$q->latest()->paginate(10)->withQueryString(),'departments'=>Department::where('company_id',$cid)->get(),'positions'=>Position::where('company_id',$cid)->get(),'filters'=>$r->only(['search','department_id','position_id','status']),'stats'=>['total'=>Employee::where('company_id',$cid)->count(),'active'=>Employee::where('company_id',$cid)->where('is_active',1)->count(),'expiring_soon'=>EmployeeLicense::where('company_id',$cid)->whereBetween('expired_date',[now(),now()->addDays(90)])->count(),'expired'=>EmployeeLicense::where('company_id',$cid)->whereDate('expired_date','<',now())->count()]]);}
 public function create(Request $r){$cid=(int)($r->user()->company_id??1);return Inertia::render('HumanResource/Employees/Create',['departments'=>Department::where('company_id',$cid)->get(),'positions'=>Position::where('company_id',$cid)->get()]);}
 public function store(Request $r){$cid=(int)($r->user()->company_id??1);$data=$r->validate(['employee_code'=>"required|max:100|unique:employees,employee_code,NULL,id,company_id,$cid",'nik'=>"nullable|max:100|unique:employees,nik,NULL,id,company_id,$cid",'full_name'=>'required|max:255','email'=>'nullable|email','phone'=>'nullable|max:30','department_id'=>'nullable|exists:departments,id','position_id'=>'nullable|exists:positions,id','employment_status'=>'nullable|max:100','is_active'=>'boolean','create_login'=>'nullable|boolean','login_email'=>'nullable|email|unique:users,email','login_password'=>'nullable|min:6']);$data['company_id']=$cid;$emp=Employee::create($data);if($r->boolean('create_login')) User::create(['name'=>$emp->full_name,'email'=>$r->login_email,'password'=>Hash::make($r->login_password ?? 'password123'),'company_id'=>$cid,'employee_id'=>$emp->id]);return redirect()->route('apps.human-resource.employees.show',$emp)->with('success','Employee created');}
 public function show(Request $r, Employee $employee){abort_unless((int)$employee->company_id===(int)($r->user()->company_id??1),404);return Inertia::render('HumanResource/Employees/Show',['employee'=>$employee->load(['department','position','licenses.licenseType','user'])]);}
 public function edit(Request $r, Employee $employee){$cid=(int)($r->user()->company_id??1);abort_unless((int)$employee->company_id===$cid,404);return Inertia::render('HumanResource/Employees/Edit',['employee'=>$employee->load('user'),'departments'=>Department::where('company_id',$cid)->get(),'positions'=>Position::where('company_id',$cid)->get()]);}
 public function update(Request $r, Employee $employee){$cid=(int)($r->user()->company_id??1);abort_unless((int)$employee->company_id===$cid,404);$data=$r->validate(['employee_code'=>"required|max:100|unique:employees,employee_code,$employee->id,id,company_id,$cid",'nik'=>"nullable|max:100|unique:employees,nik,$employee->id,id,company_id,$cid",'full_name'=>'required|max:255','email'=>'nullable|email','phone'=>'nullable|max:30','department_id'=>'nullable|exists:departments,id','position_id'=>'nullable|exists:positions,id','employment_status'=>'nullable|max:100','is_active'=>'boolean']);$employee->update($data);return back()->with('success','Employee updated');}
 public function destroy(Request $r, Employee $employee){abort_unless((int)$employee->company_id===(int)($r->user()->company_id??1),404);$employee->update(['is_active'=>false]);return back()->with('success','Employee deactivated');}}
