import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';

export default function Page({ customers, filters = {} }) {
  const onDelete = (id) => { if (confirm('Delete this customer?')) router.delete(route('customers.destroy', id)); };
  return <AppLayout><Head title="Customers" /><div className='p-6 space-y-4'>
    <div className='flex justify-between'><h1 className='text-xl font-semibold'>Customers</h1><Link href={route('customers.create')} className='px-3 py-2 bg-blue-600 text-white rounded'>Add Customer</Link></div>
    <div className='flex gap-2'><input defaultValue={filters.search||''} placeholder='Search' className='border rounded px-3 py-2' onKeyDown={(e)=>e.key==='Enter'&&router.get(route('customers.index'),{...filters,search:e.target.value},{preserveState:true})} /><select defaultValue={filters.status||''} className='border rounded px-3 py-2' onChange={(e)=>router.get(route('customers.index'),{...filters,status:e.target.value},{preserveState:true})}><option value=''>All Status</option><option value='active'>Active</option><option value='inactive'>Inactive</option></select></div>
    <div className='overflow-auto bg-white rounded border'><table className='w-full text-sm'><thead><tr className='bg-gray-50 text-left'>{['Customer Code','Customer Name','Contact Person','Phone','City','NPWP','Payment Term','Credit Limit','Status','Actions'].map(h=><th key={h} className='p-2'>{h}</th>)}</tr></thead><tbody>{customers.data.map(c=><tr key={c.id} className='border-t'><td className='p-2'>{c.customer_code}</td><td className='p-2'>{c.customer_name}</td><td className='p-2'>{c.contact_person}</td><td className='p-2'>{c.phone}</td><td className='p-2'>{c.city}</td><td className='p-2'>{c.npwp}</td><td className='p-2'>{c.payment_term_days} days</td><td className='p-2'>{Number(c.credit_limit||0).toLocaleString('id-ID',{style:'currency',currency:'IDR'})}</td><td className='p-2'><span className={`px-2 py-1 rounded text-xs ${c.status==='active'?'bg-green-100 text-green-700':'bg-gray-100 text-gray-700'}`}>{c.status}</span></td><td className='p-2 space-x-2'><Link href={route('customers.show',c.id)} className='text-blue-600'>View</Link><Link href={route('customers.edit',c.id)} className='text-amber-600'>Edit</Link><button onClick={()=>onDelete(c.id)} className='text-red-600'>Delete</button></td></tr>)}</tbody></table></div>
  </div></AppLayout>;
}
