import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
const money=(n)=>Number(n||0).toLocaleString('id-ID',{style:'currency',currency:'IDR'});
export default function Page({ salesOrder }) {
const orderStatus = String(salesOrder.status || salesOrder.status_label || '').toLowerCase().replace(/\s+/g,'_');
const hasOutstandingQty = (salesOrder.lines || []).some((line) => Number(line.qty_sold || 0) - Number(line.qty_shipped || 0) > 0);
const isShipmentStatusAllowed = ['approved','partially_shipped'].includes(orderStatus);
const canCreateShipment = isShipmentStatusAllowed && hasOutstandingQty && !['closed','cancelled'].includes(orderStatus);

return <AppLayout><Head title='Sales Order'/><div className='p-6 space-y-4'>
<div className='flex justify-between'><div><h1 className='text-xl font-semibold'>{salesOrder.number} - {salesOrder.customer?.customer_name}</h1><div className='text-sm'>{salesOrder.document_date} | {salesOrder.expected_delivery_date||'-'} | {salesOrder.warehouse?.name||'-'} | {salesOrder.price_list?.name||'-'}</div></div><span className='px-2 py-1 rounded bg-slate-100 text-xs'>{salesOrder.status_label}</span></div>
<div className='flex gap-2'>{salesOrder.can_edit&&<Link href={route('apps.sales-orders.edit',salesOrder.id)} className='border px-3 py-1'>Edit Draft</Link>}{salesOrder.can_submit&&<button className='border px-3 py-1' onClick={()=>router.post(route('apps.sales-orders.submit',salesOrder.id))}>Submit</button>}{salesOrder.can_approve&&<button className='border px-3 py-1' onClick={()=>router.post(route('apps.sales-orders.approve',salesOrder.id))}>Approve</button>}{salesOrder.can_cancel&&<button className='border px-3 py-1' onClick={()=>router.post(route('apps.sales-orders.cancel',salesOrder.id),{cancel_reason:'Cancelled from SO page'})}>Cancel</button>}<button type='button' disabled={!canCreateShipment} title={!canCreateShipment?'Create Shipment aktif saat SO Approved dan masih ada qty belum dikirim':''} className={`border px-3 py-1 ${canCreateShipment?'border-emerald-500 text-emerald-700 hover:bg-emerald-50':'opacity-50 cursor-not-allowed'}`} onClick={()=>canCreateShipment&&router.get(route('apps.sales-orders.shipments.create',salesOrder.id))}>{orderStatus==='partially_shipped'?'Continue Shipment':'Create Shipment'}</button><Link href={route('apps.customers.show',salesOrder.customer_id)} className='border px-3 py-1'>Back to Customer</Link></div>
<div className='grid md:grid-cols-4 gap-2'><div className='border p-2'>Subtotal<br/>{money(salesOrder.subtotal)}</div><div className='border p-2'>Discount<br/>{money(salesOrder.discount_total)}</div><div className='border p-2'>Tax<br/>{money(salesOrder.tax_total)}</div><div className='border p-2 font-semibold'>Grand Total<br/>{money(salesOrder.grand_total)}</div></div>
<table className='w-full border text-sm'><thead><tr><th>Item</th><th>UoM</th><th>Avail Stock</th><th>Qty Ordered</th><th>Qty Shipped</th><th>Qty Invoiced</th><th>Unit Price</th><th>Discount</th><th>Tax</th><th>Line Total</th><th>Notes</th></tr></thead><tbody>{salesOrder.lines?.map(l=><tr key={l.id}><td>{l.item?.name}</td><td>{l.uom?.name}</td><td>{l.available_stock??'Unknown'}</td><td>{l.qty_sold}</td><td>{l.qty_shipped}</td><td>{l.qty_invoiced}</td><td>{money(l.unit_price)}</td><td>{money(l.discount_amount)}</td><td>{money(l.tax_amount)}</td><td>{money(l.line_total)}</td><td>{l.notes||'-'}</td></tr>)}</tbody></table>
<div className='border p-3 text-sm'>Timeline: Created → Submitted → Approved → Shipment ({salesOrder.status==='fully_shipped'?'Fully Shipped':(salesOrder.status==='partially_shipped'?'Partial Shipment':'Not Created')}) → Invoice → Payment</div>
<div className='border p-3 text-sm'>Related Shipments: {(salesOrder.shipments||[]).length||0}</div>
</div></AppLayout>; }
