import AppLayout from '@/Layouts/AppLayout';
import { useForm } from '@inertiajs/react';

const emptyItem = { product_id:'', product_name:'', uom_id:'', qty_ordered:1, unit_price:0, discount_amount:0, tax_amount:0, line_total:0 };
export default function Form({ purchaseOrder = null, vendors = [], products = [], uoms = [] }) {
  const isEdit = !!purchaseOrder;
  const { data, setData, post, put } = useForm({ vendor_id: purchaseOrder?.vendor_id || '', po_date: purchaseOrder?.po_date || '', expected_delivery_date: purchaseOrder?.expected_delivery_date || '', notes: purchaseOrder?.notes || '', items: purchaseOrder?.items || [emptyItem] });
  const setItem = (i,k,v)=>{const items=[...data.items]; items[i]={...items[i],[k]:v}; const b=(+items[i].qty_ordered)*(+items[i].unit_price); items[i].line_total=b-(+items[i].discount_amount)+(+items[i].tax_amount); setData('items',items)};
  const totals = data.items.reduce((a,i)=>({subtotal:a.subtotal+(+i.qty_ordered*+i.unit_price),discount:a.discount+(+i.discount_amount||0),tax:a.tax+(+i.tax_amount||0),grand:a.grand+(+i.line_total||0)}),{subtotal:0,discount:0,tax:0,grand:0});
  const submit=(e)=>{e.preventDefault(); isEdit?put(`/apps/procurement/purchase-orders/${purchaseOrder.id}`):post('/apps/procurement/purchase-orders')};
  return <AppLayout><form onSubmit={submit} className='p-6 space-y-4'><h1 className='text-xl font-semibold'>{isEdit?'Edit':'Create'} Purchase Order</h1>
  <div className='grid grid-cols-2 gap-3'><select className='border p-2' value={data.vendor_id} onChange={e=>setData('vendor_id',e.target.value)}><option value=''>Pilih Vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select>
  <input type='date' className='border p-2' value={data.po_date} onChange={e=>setData('po_date',e.target.value)}/><input type='date' className='border p-2' value={data.expected_delivery_date} onChange={e=>setData('expected_delivery_date',e.target.value)}/><textarea className='border p-2' value={data.notes} onChange={e=>setData('notes',e.target.value)} /></div>
  {data.items.map((it,i)=><div key={i} className='grid grid-cols-8 gap-2'><select className='border p-1' value={it.product_id||''} onChange={e=>setItem(i,'product_id',e.target.value)}><option value=''>Product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className='border p-1' value={it.product_name||''} onChange={e=>setItem(i,'product_name',e.target.value)} placeholder='Nama'/><select className='border p-1' value={it.uom_id||''} onChange={e=>setItem(i,'uom_id',e.target.value)}><option value=''>UOM</option>{uoms.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><input type='number' className='border p-1' value={it.qty_ordered} onChange={e=>setItem(i,'qty_ordered',e.target.value)}/><input type='number' className='border p-1' value={it.unit_price} onChange={e=>setItem(i,'unit_price',e.target.value)}/><input type='number' className='border p-1' value={it.discount_amount} onChange={e=>setItem(i,'discount_amount',e.target.value)}/><input type='number' className='border p-1' value={it.tax_amount} onChange={e=>setItem(i,'tax_amount',e.target.value)}/><div className='flex items-center justify-between'><span>{it.line_total}</span><button type='button' onClick={()=>setData('items',data.items.filter((_,idx)=>idx!==i))}>x</button></div></div>)}
  <button type='button' className='px-2 py-1 border rounded' onClick={()=>setData('items',[...data.items,emptyItem])}>+ Item</button>
  <div className='text-right'>Subtotal {totals.subtotal} | Discount {totals.discount} | Tax {totals.tax} | Grand Total {totals.grand}</div>
  <button className='px-4 py-2 bg-indigo-600 text-white rounded'>Save Draft</button></form></AppLayout>;
}
