<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('document_categories',function(Blueprint $t){$t->id();$t->unsignedBigInteger('business_id')->nullable();$t->string('code');$t->string('name');$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['business_id','code']);});
Schema::create('documents',function(Blueprint $t){$t->id();$t->unsignedBigInteger('business_id')->nullable();$t->string('owner_type');$t->unsignedBigInteger('owner_id');$t->foreignId('document_category_id')->nullable()->constrained('document_categories');$t->foreignId('document_type_id')->nullable()->constrained('document_types');$t->string('title');$t->string('document_number')->nullable();$t->date('issue_date')->nullable();$t->date('expiry_date')->nullable();$t->string('file_path');$t->string('original_file_name')->nullable();$t->string('stored_file_name')->nullable();$t->string('mime_type')->nullable();$t->unsignedBigInteger('file_size')->nullable();$t->string('storage_disk')->default('local');$t->string('status')->default('uploaded');$t->string('visibility')->default('internal');$t->unsignedBigInteger('uploaded_by')->nullable();$t->unsignedBigInteger('verified_by')->nullable();$t->dateTime('verified_at')->nullable();$t->text('rejected_reason')->nullable();$t->text('notes')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();$t->index('business_id');$t->index(['owner_type','owner_id']);$t->index('document_type_id');$t->index('document_category_id');$t->index('status');$t->index('expiry_date');});
Schema::table('document_types',function(Blueprint $t){if(!Schema::hasColumn('document_types','business_id'))$t->unsignedBigInteger('business_id')->nullable()->after('id');if(!Schema::hasColumn('document_types','document_category_id'))$t->foreignId('document_category_id')->nullable()->after('business_id')->constrained('document_categories');if(!Schema::hasColumn('document_types','applicable_owner_types'))$t->json('applicable_owner_types')->nullable();if(!Schema::hasColumn('document_types','is_expirable'))$t->boolean('is_expirable')->default(false);if(!Schema::hasColumn('document_types','requires_verification'))$t->boolean('requires_verification')->default(false);if(!Schema::hasColumn('document_types','max_file_size_mb'))$t->integer('max_file_size_mb')->nullable();if(!Schema::hasColumn('document_types','allowed_mime_types'))$t->json('allowed_mime_types')->nullable();});
Schema::create('document_audit_logs',function(Blueprint $t){$t->id();$t->unsignedBigInteger('business_id')->nullable();$t->foreignId('document_id')->constrained('documents');$t->string('action');$t->json('old_values')->nullable();$t->json('new_values')->nullable();$t->unsignedBigInteger('performed_by')->nullable();$t->dateTime('performed_at');$t->string('ip_address')->nullable();$t->text('user_agent')->nullable();});
}
public function down():void{Schema::dropIfExists('document_audit_logs');Schema::dropIfExists('documents');Schema::dropIfExists('document_categories');}};
